# Generated by Django 5.1.1 on 2024-09-20 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_poststat_rate_is_suspected_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poststat',
            old_name='average_rate',
            new_name='average_rates',
        ),
    ]
