# Generated by Django 5.1.1 on 2024-09-20 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_poststat_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='poststat',
            table=None,
        ),
    ]
